### ISSUE TITLE
Linear angles

### ISSUE THREAD

**Issue by RMeli** [RMeli/irc#19]

**Comment by peterbygrave** [comment]
Implement Wilson B matrix contributions from angles that are >170/175 by splitting the angle in two and using a external reference for each.

Need to put an enum class in `struct Angle` to keep track of what is it.

Need a test system as well

**Comment by RMeli** [comment]
The `LinearAngle` object in [GeomeTRIC](https://github.com/leeping/geomeTRIC/blob/master/geometric/internal.py) can be helpful to complete this task.

**Comment by RMeli** [comment]
A C++ implementation of Wilson's B matrix for [linear angles](https://github.com/psi4/psi4/tree/master/psi4/src/psi4/optking/bend.cc).

**Comment by RMeli** [comment]
Fixed by @peterbygrave with PR #26
