### ISSUE TITLE
Non-template functions need to inlined

### ISSUE THREAD

**Issue by peterbygrave** [RMeli/irc#25]
The library is header only and needs to have all non template functions as `inline` e.g. 
`double pirange_rad(double angle) noexcept`

Just found this because I have two .cpp files that `#include libirc/irc_*.h`

**Comment by peterbygrave** [comment]
@RMeli If you can let me know if you're likely to fix it this evening (I of course do not expect this), otherwise I can get it done no problem because I need to merge BFGS branch.

**Comment by RMeli** [comment]
@peterbygrave `pirange_rad` is `inline` in the last version. There were a few non-inline non-template functions in `periodic_table.h` and they are now fixed. Let me know if this solves your issue.

**Comment by peterbygrave** [comment]
Thanks, all builds now.

Found out from google that you have to inline class constructors if they are defined outside of the class body.

**Comment by RMeli** [comment]
Cool. Which compiler were you using? Because I had no problems with Clang when including the library in another project.
